// ngl brobro I was not about to sit up here and type all of this manually so I'm putthat that claude subscription (lumo AI cause I use proton) to work 🥱✌️✌️
pub fn get_continent(country: &str) -> Option<&'static str> {
    match country {
        // Europe
        "United Kingdom"
        | "Germany"
        | "France"
        | "Spain"
        | "Italy"
        | "Netherlands"
        | "Poland"
        | "Sweden"
        | "Norway"
        | "Finland"
        | "Denmark"
        | "Portugal"
        | "Greece"
        | "Czech Republic"
        | "Belgium"
        | "Austria"
        | "Switzerland"
        | "Romania"
        | "Hungary"
        | "Ireland"
        | "Ukraine"
        | "Russia"
        | "Slovakia"
        | "Bulgaria"
        | "Serbia"
        | "Croatia"
        | "Bosnia and Herzegovina"
        | "Slovenia"
        | "Albania"
        | "North Macedonia"
        | "Montenegro"
        | "Lithuania"
        | "Latvia"
        | "Estonia"
        | "Luxembourg"
        | "Malta"
        | "Iceland"
        | "Andorra"
        | "Monaco"
        | "San Marino"
        | "Vatican City"
        | "Liechtenstein" => Some("EU"),
        
        "Japan" 
        => Some("JPN"),

        "South Korea"
        => Some("KOR"),

        // Asia
        "China"
        | "India"
        | "North Korea"
        | "Thailand"
        | "Vietnam"
        | "Indonesia"
        | "Malaysia"
        | "Philippines"
        | "Singapore"
        | "Bangladesh"
        | "Pakistan"
        | "Iran"
        | "Iraq"
        | "Saudi Arabia"
        | "Turkey"
        | "Israel"
        | "United Arab Emirates"
        | "Afghanistan"
        | "Kazakhstan"
        | "Myanmar"
        | "Yemen"
        | "Jordan"
        | "Lebanon"
        | "Syria"
        | "Qatar"
        | "Kuwait"
        | "Oman"
        | "Bahrain"
        | "Georgia"
        | "Armenia"
        | "Azerbaijan"
        | "Uzbekistan"
        | "Turkmenistan"
        | "Kyrgyzstan"
        | "Tajikistan"
        | "Mongolia"
        | "Cambodia"
        | "Laos"
        | "Brunei"
        | "Timor-Leste"
        | "East Timor"
        | "Nepal"
        | "Bhutan"
        | "Sri Lanka"
        | "Maldives"
        | "Cyprus" => Some("ASIA"),
        
        // North America
        "United States"
        | "Canada"
        | "Mexico"
        | "Guatemala"
        | "Cuba"
        | "Haiti"
        | "Dominican Republic"
        | "Honduras"
        | "Nicaragua"
        | "Costa Rica"
        | "Panama"
        | "Jamaica"
        | "Trinidad and Tobago"
        | "Bahamas"
        | "Barbados"
        | "Saint Lucia"
        | "Grenada"
        | "Saint Vincent and the Grenadines"
        | "Antigua and Barbuda"
        | "Dominica"
        | "Saint Kitts and Nevis"
        | "Belize"
        | "El Salvador" => Some("NA"),
        
        // South America
        "Brazil"
        | "Argentina"
        | "Colombia"
        | "Peru"
        | "Venezuela"
        | "Chile"
        | "Ecuador"
        | "Bolivia"
        | "Paraguay"
        | "Uruguay"
        | "Guyana"
        | "Suriname"
        | "French Guiana" => Some("SA"),
        
        // Africa
        "Egypt"
        | "Nigeria"
        | "South Africa"
        | "Kenya"
        | "Ethiopia"
        | "Morocco"
        | "Algeria"
        | "Tunisia"
        | "Ghana"
        | "Tanzania"
        | "Uganda"
        | "Zimbabwe"
        | "Angola"
        | "Senegal"
        | "Cameroon"
        | "Libya"
        | "Mozambique"
        | "Madagascar"
        | "Democratic Republic of the Congo"
        | "Republic of the Congo"
        | "Sudan"
        | "South Sudan"
        | "Somalia"
        | "Zambia"
        | "Mali"
        | "Burkina Faso"
        | "Niger"
        | "Chad"
        | "Central African Republic"
        | "Guinea"
        | "Benin"
        | "Togo"
        | "Sierra Leone"
        | "Liberia"
        | "Ivory Coast"
        | "Mauritania"
        | "Namibia"
        | "Botswana"
        | "Lesotho"
        | "Eswatini"
        | "Mauritius"
        | "Comoros"
        | "Djibouti"
        | "Eritrea"
        | "Gabon"
        | "Equatorial Guinea"
        | "Cape Verde"
        | "Sao Tome and Principe"
        | "Rwanda"
        | "Burundi"
        | "Malawi"
        | "Gambia" => Some("AFR"),
        
        // Oceania
        "Australia"
        | "New Zealand"
        | "Papua New Guinea"
        | "Fiji"
        | "Solomon Islands"
        | "Samoa"
        | "Vanuatu"
        | "Tonga"
        | "Palau"
        | "Micronesia"
        | "Marshall Islands"
        | "Kiribati"
        | "Tuvalu"
        | "Nauru"
        | "Vanuatu"
        | "Cook Islands"
        | "French Polynesia"
        | "New Caledonia"
        | "Samoa" => Some("OCE"),
        
        _ => None,
    }
}